#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : freedv
Version  : 1.3.1
Release  : 2
URL      : https://hobbes1069.fedorapeople.org/freetel/freedv/freedv-1.3.1.tar.xz
Source0  : https://hobbes1069.fedorapeople.org/freetel/freedv/freedv-1.3.1.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : CC-BY-4.0 LGPL-2.1
Requires: freedv-bin = %{version}-%{release}
Requires: freedv-data = %{version}-%{release}
Requires: freedv-license = %{version}-%{release}
BuildRequires : alsa-lib-dev
BuildRequires : buildreq-cmake
BuildRequires : codec2-dev
BuildRequires : glibc-dev
BuildRequires : hamlib-dev
BuildRequires : libsamplerate-dev
BuildRequires : libsndfile-dev
BuildRequires : pkgconfig(portaudio-2.0)
BuildRequires : speexdsp-dev
BuildRequires : subversion
BuildRequires : wxWidgets
BuildRequires : wxWidgets-dev

%description
==================================
==================================
This document describes how to build the FreeDV GUI program for
various operating systems.  See also:

%package bin
Summary: bin components for the freedv package.
Group: Binaries
Requires: freedv-data = %{version}-%{release}
Requires: freedv-license = %{version}-%{release}

%description bin
bin components for the freedv package.


%package data
Summary: data components for the freedv package.
Group: Data

%description data
data components for the freedv package.


%package license
Summary: license components for the freedv package.
Group: Default

%description license
license components for the freedv package.


%prep
%setup -q -n freedv-1.3.1
cd %{_builddir}/freedv-1.3.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1572645329
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake .. -DUSE_STATIC_CODEC2=FALSE \
-DUSE_STATIC_DEPS=FALSE
make  %{?_smp_mflags}  VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1572645329
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/freedv
cp %{_builddir}/freedv-1.3.1/COPYING %{buildroot}/usr/share/package-licenses/freedv/0468d1cb0e40500dc98fa86141431a9f9e088c2b
cp %{_builddir}/freedv-1.3.1/contrib/LICENSE %{buildroot}/usr/share/package-licenses/freedv/e9101bd4e253c0f7da54e8f581cf72322df10162
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/freedv

%files data
%defattr(-,root,root,-)
/usr/share/applications/freedv.desktop
/usr/share/icons/hicolor/128x128/apps/freedv.png
/usr/share/icons/hicolor/256x256/apps/freedv.png
/usr/share/icons/hicolor/48x48/apps/freedv.png
/usr/share/icons/hicolor/64x64/apps/freedv.png

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/freedv/0468d1cb0e40500dc98fa86141431a9f9e088c2b
/usr/share/package-licenses/freedv/e9101bd4e253c0f7da54e8f581cf72322df10162
